config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  resources :users
  resources :relations do
    member do
      get :complete, :verify
    end
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signup' => 'users#new'
  get 'logout' => 'sessions#destroy'
  root 'welcome#home'  
  
end

app/models/relation.rb
class Relation < ActiveRecord::Base

  belongs_to :user
  belongs_to :patner, class_name: "User"
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user
  belongs_to :relation

  scope :group_tasks,
    lambda { |relation_id, user_id| where("relation_id = ? AND user_id = ?", relation_id, user_id) }
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  has_secure_password
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },  
                                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 2 }

  has_many :actives, class_name: "Relation", dependent: :destroy
  has_many :patners, through: :actives
  has_many :passives, class_name: "Relation",
                      foreign_key: "patner_id", dependent: :destroy
  has_many :users, through: :passives

  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController

  def new
  end

  def create
    @partner = User.find_by(email: params[:email])
    @user = User.find_by(id: params[:user_id])
    @active = Relation.new(user_id: @user.id, patner_id: @partner.id)
    @active.save
  end

  def destroy
  end

  def complete
    @relation= Relation.find(params[:id])                                                             
  end

  def verify
    @relation = Relation.find(params[:relation_id]) 
    @partner = User.find_by(email: params[:email]) 
    if (@partner.id == @relation.patner_id &&  params[:relation_id] == params[:account_id])
      @relation.update_attributes(verified: true)
      redirect_to @partner
    else
      puts "not verified"
      render 'complete'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to login_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @relation= Relation.find(params[:relation_id])
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(relation_id: params[:relation_id], name: params[:task][:name])
    @task.save 
    redirect_to current_user
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:show, :edit, :delete] 

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Welcome to the Task Tracker App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  private 

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:error] = "Please sign in."
        redirect_to login_path 
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id]=user.id
  end

  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id) 
    current_user = nil
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>The <a href="http://localhost:3000/">Task Tracker</a> by <a href="https://twitter.com/SasikalaRavicha">Sasikala</a></small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TASK TRACKER", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Tracker</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relations/complete.html.erb
<%= @relation.id %>
<%= form_tag verify_relation_path, :method => :get do  %>
  <%= hidden_field_tag :relation_id, @relation.id %> 
  <%= text_field_tag :account_id %>
  <%= email_field_tag :email %>
  <%= submit_tag("link to partner")%>
<% end %>

app/views/relations/create.html.erb
<%= @partner.name%>
<%= @partner.id%>
<%= @user.name%>
<%= @user.id%>

app/views/relations/destroy.html.erb
<h1>Relations#destroy</h1>
<p>Find me in app/views/relations/destroy.html.erb</p>

app/views/relations/new.html.erb
<%= form_for(current_user.actives.build) do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= email_field_tag :email %>
  <%= f.submit "Create a partner" %>
<% end %>

app/views/relations/verify.html.erb
<p>verified</p>
<%= @relation.id %>
<%= params[:account_id] %>
<%= @partner.id%>
<%= @relation.patner_id%>
<%= link_to "logout", logout_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  The form contains <%= pluralize(@user.errors.count, "error") %>.
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/new.html.erb
<%= params[:relation_id]%>
<%= current_user.id%>
<%= form_for(@task) do |f| %>
  <%= hidden_field_tag :relation_id, @relation.id %>
  <%= f.text_field :name %>
  <%= f.submit "Create a task" %>
<% end %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/_createpartner.html.erb
<%= form_for(current_user.actives.build) do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= email_field_tag :email %>
  <%= f.submit "Create a partner" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.name, user %><br/>
<% end %>
<%= link_to "New User", new_user_path %>
<%= link_to "login", login_path%>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
  
  <%= render 'shared/error_messages' %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "Create my account", class: "btn btn-primary" %>

<% end %>
   

app/views/users/show.html.erb
<%= @user.name%><br/>
<%= @user.email%><br/>
<%= current_user.name %>
<%= current_user.email %>

<%= button_to "Create a partner", new_relation_path, :method => :get %>
 <br/>
<% @user.passives.each do |relation| %>
  <% unless relation.verified %>
    Relation_id: <%= relation.id %><br/>
    <%= link_to "link_to_partner #{User.find(relation.user_id).name}", complete_relation_path(relation), :method => :get  %>
  <% end %>
<% end %>
<br/>
Final patner:<br/>
<%  @user.actives.each do |relation| %>
  <% if relation.verified %>
    <% user = User.find(relation.patner_id)%><br/>
    <%= user.name %>
    <%= Task.group_tasks(relation.id, current_user.id).pluck(:name)%>
    <%= link_to "Add task", new_task_path(relation_id: relation.id) %><br/>
    <%= user.name %>
    <%= user.id %>
    <%= relation.id %>
    <%= Task.group_tasks(relation.id, user.id).pluck(:name)%>
  <% end %>
<% end %>

<%  @user.passives.each do |relation| %>
  <% if relation.verified %>
    <% user = User.find(relation.user_id)%><br/>
    <%= user.name %>
    <%= Task.group_tasks(relation.id, current_user.id).pluck(:name)%>
    <%= link_to "Add task", new_task_path(relation_id: relation.id) %><br/>
    <br/> Partners:
    <%= user.name %>
    <%= user.id %>
    <%= relation.id %>
    <%= Task.group_tasks(relation.id, user.id).pluck(:name)%>
  <% end %>
<% end %>
<br/>
<%= link_to "back", users_path%>
<br/>
<%= link_to "logout", logout_path %> 

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Task Tracking System</h1>
  <p>You will love to track the tacks along with your friends and friends</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
 